# docker-compose
version: "3.9"
services:
  php-fpm:
    image: soren.sjostrom/apline-php-fpm:latest
    container_name: php-fpm
    build:
      context: .
      dockerfile: ./Dockerfile
    logging:
      options:
        max-size: "10M"
        max-file: "3"
    volumes:
      - ./:/var/www/html
