name: devel
on:
  pull_request:
    branches:
      - devel
    paths:
      - alpine-php-fpm/**
  push:
    branches:
      - devel
    paths:
      - alpine-php-fpm/**

jobs:
  php:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build:
          - amd64
        include:
          - build: amd64
            arch: linux/amd64
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      -
        name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: alpine-php-fpm-${{ matrix.arch }}-buildx-${{ github.sha }}
          restore-keys: |
            fpm-${{ matrix.arch }}-buildx-
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and Test
        uses: docker/build-push-action@v3
        with:
          push: false
          context: .
          platforms: ${{ matrix.arch }}
          file: 8.2-php-fpm/Dockerfile
          tags: sorensj/alpine-php-fpm:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
