name: release-v8.2
on:
  push:
    tags:
      - 'v8.2.[0-9]+'
      - 'v8.2.[0-9]+-beta.[0-9]+'

jobs:
  docker-build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build:
          - amd64
        include:
          - build: amd64
            arch: linux/amd64
    name: PHP 8.2 (${{ matrix.build }})
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: sorensj/alpine-php-fpm
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{major}}.{{minor}}-${{ matrix.build }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          platforms: ${{ matrix.arch }}
          file: 8.2-php-fpm/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}

  docker-manifest:
    needs: docker-build
    runs-on: ubuntu-22.04
    steps:
      - name: Set envs
        run: |
          github_ref=${GITHUB_REF#refs/tags/}
          SEMVER=${github_ref##*v}
          echo "SEMVER=${SEMVER}" >> $GITHUB_ENV
          echo "SEMVER_MAJOR=${SEMVER%.*.*}" >> $GITHUB_ENV
          echo "SEMVER_MINOR=${SEMVER%.*}" >> $GITHUB_ENV
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push semver minor alias
        run: |
          docker manifest create \
            sorensj/alpine-php-fpm:$SEMVER_MINOR \
              --amend sorensj/php-fpm:$SEMVER_MINOR-amd64 \
          docker manifest push sorensj/alpine-php-fpm:$SEMVER_MINOR
      -
        name: Push latest (PHP 8.2 or newer)
        run: |
          docker manifest create \
            sorensj/alpine-php-fpm:latest \
              --amend sorensj/alpine-php-fpm:$SEMVER_MINOR-amd64 \
          docker manifest push sorensj/alpine-php-fpm:latest
      -
        name: Pull all images
        run: |
          docker pull sorensj/alpine-php-fpm:$SEMVER_MINOR-amd64
      -
        name: Push semver alias
        run: |
          docker manifest create \
            sorensj/php-fpm:$SEMVER \
              --amend sorensj/alpine-php-fpm:$SEMVER_MINOR-amd64 \
          docker manifest push sorensj/alpine-php-fpm:$SEMVER   
      -
        name: Push semver major alias (PHP 8.2 or newer)   
        run: |
          docker manifest create \
            sorensj/php-fpm:$SEMVER_MAJOR \
              --amend sorensj/php-fpm:$SEMVER_MINOR-amd64 \
          docker manifest push sorensj/alpine-php-fpm:$SEMVER_MAJOR
